---
language: node_js
node_js:
- '0.10'
jdk:
- oraclejdk7
before_script:
- npm install -g grunt-cli
before_install:
- wget dist.neo4j.org/neo4j-community-2.1.7-unix.tar.gz
- tar -xzf neo4j-community-2.1.7-unix.tar.gz
- neo4j-community-2.1.7/bin/neo4j start
addons:
  sauce_connect: true
before_deploy:
- neo4j-community-2.1.7/bin/neo4j stop
- rm -rf neo4j-community-2.1.7 neo4j-community-2.1.7-unix.tar.gz
deploy:
  provider: heroku
  app: agilejs-team-3
  skip_cleanup: true
  api_key:
    secure: ! 'ncCAxXR1K7wGus6oUIVPGgjfaHTvYcqb7uoSh9OhV3vAD9gX2ZXwJaEY/G5r

      Gc79HhFm5BA0HAhM/AWnpi6yt7RYDCnAZ+CCNQIV7dXRcGWHL8hG/jrzS2Ab

      f/lXNRQyJ5wsn3OQPT7YZnfzmtVcWZY2CjyUHpI/3BkV0LKg7/Y='
env:
  global:
  - secure: ! 'lYknLcJrXiEp3nYPd80EyJhmbLXjs75UMfXLDW4W9UbPQAVr8OtUVK3LTKaO

      MPWsOdr3GAHwzgOY4fJ1ALbxmsdPbx5KdYG2oNH3MLyKOFQkXU6P67OYiSTo

      e3s130EU8wSwnBwamwYgHMQ4BlKht/6PBr3AprhjNDUfeuYn4BI='
  - secure: ! 'oYH3mYM8pCCnd6lDzi/5isM9/EVwQdjS5Cxofi215y2LGOUBmvQuuaConfQt

      QHSFjnxH3IYrJAmrZkxesGirVEigp1oeRqiFHWthtEZwpstAv2enW2DVd1vX

      EihafYj/T7AqsPpuSUmjDhJnE/Y3WlX0k/VFemE6yRQ8X1YvSl4='
